### PR TITLE
Mirrorlist: rework html page

### PR DESCRIPTION
**Pull request by kib**
This reworks the html page of the mirrorlist. (etix/mirrorbits#9)

Changes:
- show more information, direct file download links and 'common names' for the mirrors.
- make better usage of the space, especially on larger monitors.
- update the used API for the piechart to 1.1

These changes are live on http://mirrors.kodi.tv/addons/isengard/addons.xml?mirrorlist and can be previewed there.

### CODE REVIEW

**Comment by kib** [comment]
pingback: etix/mirrorlist#9

**Comment by kib** [comment]
@etix this has been rebased and should apply cleanly now.

**Comment by etix** [comment]
The Google Maps image is stretched because the URL generated by the core still contains size=520x320 whereas in the template the size is 600x320. You should probably modify that too.

**Comment by kib** [comment]
I was just trying to make my country a bit wider :+1: 

*In reality I have just mucked up when i moved the map to the left...*

**Comment by etix** [comment]
Thanks a lot for the contribution!

**Pull request merged**
