### PR TITLE
Fix issue with LRU cache

### PR DESCRIPTION
**Pull request by elboulangero**
Fix issue reported at https://github.com/etix/mirrorbits/issues/114

### CODE REVIEW

**Comment by jbkempf** [comment]
Shouldn't the display commit be in a different PR?

**Comment by elboulangero** [comment]
Indeed, I opened a separate PR: https://github.com/etix/mirrorbits/pull/160

**Comment by lazka** [comment]
I've been using this in prod for a day, and it seems to work as advertised.

**Comment by elboulangero** [comment]
Thanks for trying it! We also have it running in prod for a week now, so far so good.

**Pull request merged**
