### PR TITLE
Evaluate If-Modified-Since header

### PR DESCRIPTION
**Pull request by ott**
It was request in issue #115 to support the If-Modified-Since header. This is a first attempt to evaluate the If-Modified-Since header.

### CODE REVIEW

**Comment by jbkempf** [comment]
That looks to me. I need to check the spec, but it seems logical.

**Comment by elboulangero** [comment]
Tested and it doesn't work. The code added is good, however the issue is that when `checkIfModifiedSince` is called, we don't know yet the mod time of the file. The function `fileInfo := filesystem.NewFileInfo(urlPath)` only initialize the struct with the file path and nothing else  (check the code in question at https://github.com/etix/mirrorbits/pull/131/files#diff-c7bd264032bb4b6d96f25a74e79e88d7c9842f310bea423fb54f76297919a8efR287-R293)

I added the missing bits and propose a new MR: https://github.com/etix/mirrorbits/pull/169

**Comment by elboulangero** [comment]
This one can be closed as https://github.com/etix/mirrorbits/pull/169 was merged

**Comment by jbkempf** [comment]
And #169 is merged. Issue fixed.

**Pull request closed without merging**
